---
- name: Create docker
  hosts: [debian_group]

  tasks:
    - name: Install docker
      pip:
        name: docker
        extra_args: --break-system-packages

    - docker_container:
        name: app
        image: task2_app
        ports:
          - 80:80
        command: python3 main.py