pipeline {
    agent any

    stages {

        stage('Clone repository with app') {
            steps {
                git branch: 'task4-develop', url: 'https://github.com/dubter/SberTech-Industrial-Development-Course.git'
            }
        }

        stage('Run unit tests') {
            steps {
                sh "cd src && go test ./... -coverprofile=coverage.out"
            }
        }

        stage('Report allure') {
            steps {
                allure([
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'src/allure-results']]
                ])
            }
        }

        stage('Sonar') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    tool name: 'maven', type: 'maven'
                    sh 'mvn clean sonar:sonar'
                }
            }
        }

        stage('Deploy app') {
            steps {
                sh "cd /inst && ansible-playbook deploy.yml --extra-vars app_home=${env.WORKSPACE}"
            }
        }

    }

    post {
        always {
            echo 'Done'
        }
    }
}
