version: '3.9'

services:
  app:
    build: ./src
    image: task2_app
    container_name: app
    ports:
      - 80:80
  ansible:
    build: ./ansible
    command: ansible-playbook DockerPlaybook.yml -i inventory.hosts
    volumes:
      - /var/run/docker.sock://var/run/docker.sock